---
title: "Biomass"
author: "Abby Lewis"
date: "2026-02-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load packages and data

# Packages
library(tidyverse)
library(readxl)
source("hm_style.R")

# Biomass
files <- list.files("../Raw_data/biomass", full.names = T)
agb <- files[grepl("aboveground", files)]
df <- agb %>%
  map(read_csv, show_col_types = F) %>%
  bind_rows() %>%
  mutate(
    chamber_ref = as.numeric(str_extract(Chamber, "[0-9]+")),
    chamber_ref = factor(chamber_ref,
      levels = 1:12,
      labels = 1:12
    ),
    `Measurement type` = ifelse(grepl("Ref", Chamber), "Reference", "Chamber")
  )

df_25 <- df %>%
  filter(Year == 2025)
```

```{r}
flux <- read_csv(here::here("processed_data", "L2- partitioned_and_gap_filled_all.csv")) %>%
  mutate(GPP_filled= GPP_filled * (60 * 60))

flux_25 <- flux %>%
  filter(TIMESTAMP < "2025-08-01")
  
n_days_25 <- as.numeric(difftime(max(flux_25$TIMESTAMP),
  min(flux_25$TIMESTAMP),
  units = "days"
))

# Calculate total GPP
gpp_25 <- flux_25 %>%
  group_by(MIU_VALVE) %>%
  summarize(
    n = sum(!is.na(GPP_filled)),
    annual = sum(GPP_filled, na.rm = T) /
      n / 1000 / 1000 * (n_days_25 * 24) * 6.022, #g/m2/y
    min = min(TIMESTAMP),
    max = max(TIMESTAMP)) %>%
  left_join(df_25 %>%
              mutate(Chamber = as.numeric(Chamber)), by = c("MIU_VALVE" = "Chamber"))
lm25 <- lm(Above.g.m2~annual, data = gpp_25)
gpp_25$predicted_AGB_g_m2 <- predict(lm25, gpp_25)

p <- gpp_25 %>%
  ggplot(aes(x = Above.g.m2, y = annual)) +
  geom_point(aes(color = MIU_VALVE)) +
  geom_smooth(method = "lm")

plotly::ggplotly(p)

flux_26 <- flux %>%
  filter(TIMESTAMP > "2026-03-17",
         TIMESTAMP < "2026-08-06")
  
n_days_26 <- as.numeric(difftime(max(flux_26$TIMESTAMP),
  min(flux_26$TIMESTAMP),
  units = "days"
))

# Calculate total GPP
gpp_26 <- flux_26 %>%
  group_by(MIU_VALVE) %>%
  summarize(
    n = sum(!is.na(GPP_filled)),
    annual = sum(GPP_filled, na.rm = T) /
      n / 1000 / 1000 * (n_days_26 * 24) * 6.022,
    min = min(TIMESTAMP),
    max = max(TIMESTAMP))
gpp_26$predicted_AGB_g_m2 <- predict(lm25, gpp_26)

predictions <- bind_rows(gpp_26, gpp_25) %>%
  mutate(Year = year(min),
         MIU_VALVE = factor(MIU_VALVE)) %>%
  select(MIU_VALVE, Above.g.m2, predicted_AGB_g_m2, Year) %>%
  pivot_longer(-c(MIU_VALVE, Year)) %>%
  mutate(name = recode_values(name,
                              "Above.g.m2"~"Observed",
                              "predicted_AGB_g_m2"~"Predicted")) 

predictions %>%
  ggplot(aes(x = Year, y = value, color = name))+
  geom_point()+
  geom_line()+
  geom_hline(yintercept = 0)+
  ylab("Aboveground biomass (g/m2)")+
  scale_x_continuous(breaks = c(2025, 2026),
                     limits = c(2024.5, 2026.5))+
  facet_wrap(~MIU_VALVE)+
  egg::theme_article()

predictions %>%
  mutate(Chamber = factor(MIU_VALVE,
                          levels = 1:12,
                          labels = chamber_labels)) %>%
  pivot_wider() %>%
  ggplot(aes(x = Observed, y = Predicted, color = Chamber))+
  geom_point()+
  geom_abline()+
  egg::theme_article()+
  coord_fixed(ratio = 1)+
  scale_color_manual(values = color.gradient)+
  xlim(c(400, 2000))+
  ylim(c(400, 2000))

evi <- read_csv(here::here("processed_data", "EVI_2026.csv")) %>%
  filter(!duplicated(Date))

evi %>%
  filter(doy > yday("2026-03-01")) %>%
  mutate(year = year(Date)) %>%
  ggplot(aes(x = doy, color = as.factor(year)))+
  geom_line(aes(y = evi_predicted))+
  geom_point(aes(y= evi_observed))+
  ylab("EVI")+
  egg::theme_article()
```

