---
title: "HM_figures"
author: "Abby Lewis"
date: "2026-01-20"
output: html_document
---

Load data and packages

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(data.table)
source("../analysis/hm_style.R")
source("../R/make_lm_label.R")

part <- read_csv(here::here("processed_data", "L2- partitioned_and_gap_filled.csv")) %>%
  rename(DateTime = TIMESTAMP) %>%
  mutate(
    CH4_umol_m2_h = CH4_filled * (60 * 60),
    CO2_umol_m2_h = NEE * (60 * 60), # h instead of s
    DateTime = with_tz(DateTime, "EST"),
    MIU_VALVE = factor(MIU_VALVE,
      levels = chamber_levels[1:2],
      labels = chamber_labels2[1:2]
    ),
    date = as_date(DateTime)
  ) %>%
  filter(DateTime <= "2025-11-15")

met <- read_csv("../processed_data/met_2025_gapfilled.csv") %>%
  mutate(TIMESTAMP = with_tz(TIMESTAMP, "EST"))

soil_temp <- read_csv(here::here("processed_data", "soil_temp.csv"))  %>%
  mutate(MIU_VALVE = factor(MIU_VALVE,
                            levels = chamber_levels,
                            labels = chamber_labels2
  )) %>%
  mutate(timestamp = with_tz(timestamp, "EST"))

n_days = as.numeric(difftime(max(part$DateTime),min(part$DateTime), units = "days"))

modzner <- read_csv(here::here("Raw_data", "from_tom.csv"))
```

Summary stats

```{r}
setDT(part)
setDT(modzner)

# Set compound keys (group + time)
setkey(part, DateTime)
setkey(modzner, Time)

max_diff <- 60 * 10  # 10 minutes (seconds)

p_to_m <- modzner[
  part,
  on = .(Time = DateTime),
  roll = max_diff,
  allow.cartesian = TRUE
]

m_to_p <- part[
  modzner,
  on = .(DateTime = Time),
  roll = max_diff,
  allow.cartesian = TRUE
]

merged <- rbindlist(list(p_to_m, m_to_p), fill = TRUE)

merged %>%
  ggplot(aes(x = CH4_filled, y = flux_ch4)) +
  geom_point() +
  facet_grid(collar ~ MIU_VALVE)
```
