---
title: "EDM"
author: "Abby Lewis"
date: "2026-02-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rEDM)
```

```{r}
target <- read_csv("../processed_data/partitioned_co2.csv") %>%
  rename(TIMESTAMP = DateTime)
met <- read_csv("../processed_data/met_2025_dashboard.csv") %>%
              mutate(Salinity = ifelse(year(TIMESTAMP) == 2025 & 
                                         as.numeric(Salinity) < 6, 
                                       NA, Salinity))
wl <- read_csv("../processed_data/water_level_dashboard.csv")
evi <- read_csv("../processed_data/evi.csv")

# Combine
df <- target %>%
  mutate(time_join = round_date(TIMESTAMP, "15 minutes"),
         date_join = date(TIMESTAMP)) %>%
  left_join(met %>% rename(time_join = TIMESTAMP)) %>%
  left_join(wl %>% rename(time_join = TIMESTAMP)) %>%
  left_join(evi %>% rename(date_join = Date)) %>%
  filter(CH4 > -0.1,
         !is.na(TIMESTAMP)) %>%
  mutate(CH4_raised = CH4-min(CH4, na.rm = T)+0.05,
         #CH4 = log(CH4_raised),
         CH4 = CH4_raised,
         GPP = ifelse(is_night, 0, GPP)
         )


# Interpolate to consistent timestep
setDT(df)
df[, TIMESTAMP := as.POSIXct(TIMESTAMP)]

make_grid <- function(g) {
  data.table(
    TIMESTAMP = seq(min(g$TIMESTAMP), max(g$TIMESTAMP), by = "130 min"),
    MIU_VALVE = g$MIU_VALVE[1]
  )
}

grid <- df[, make_grid(.SD), by = MIU_VALVE]

setkey(grid, MIU_VALVE, TIMESTAMP)
setkey(df, MIU_VALVE, TIMESTAMP)

ch4 <- df[grid, roll = 7200] # 7200 seconds

# Plot specifications
chamber_levels2 = c("Ch. 1 (+0 ºC)", "Ch. 2 (+0 ºC)", "Ch. 3 (+0.75 ºC)", 
                    "Ch. 4 (+1.5 ºC)", "Ch. 5 (+2.25 ºC)", "Ch. 6 (+2.25 ºC)", 
                    "Ch. 7 (+3.0 ºC)", "Ch. 8 (+3.75 ºC)", "Ch. 9 (+3.75 ºC)",
                   "Ch. 10 (+4.5 ºC)", "Ch. 11 (+5.25 ºC)", "Ch. 12 (+6.0 ºC)")

color.gradient=c('blue4','blue3','turquoise4','lightseagreen',
                 'mediumseagreen','limegreen','yellowgreen','yellow2',
                 'darkgoldenrod2','darkorange2','orangered1','red2')
```

