---
title: "HM_figures"
author: "Abby Lewis"
date: "2026-01-20"
output: html_document
---

Load data and packages

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggridges)

part <- read_csv(here::here("processed_data", "partitioned_co2.csv"))
chamber_levels = c("c_1_amb", "c_2_amb", "c_3_e0.75", "c_4_e1.5", "c_5_e2.25",
                   "c_6_e2.25", "c_7_e3.0", "c_8_e3.75", "c_9_e3.75",
                   "c_10_e4.5", "c_11_e5.25", "c_12_e6.0")

color.gradient=c('blue4','blue3','turquoise4','lightseagreen',
                 'mediumseagreen','limegreen','yellowgreen','yellow2',
                 'darkgoldenrod2','darkorange2','orangered1','red2')
```

```{r}
part %>%
  mutate(MIU_VALVE = factor(MIU_VALVE, levels = 1:12, 
                            labels = chamber_levels)) %>%
  ggplot(aes(x = CH4, y = MIU_VALVE, fill = MIU_VALVE))+
  geom_vline(xintercept = 0, color = "grey50")+
  stat_density_ridges(
    geom = "density_ridges",
    quantiles = 2,
    quantile_lines = TRUE,
    n = 2048,
    rel_min_height = 0.005,
    scale = 0.9
  ) +
  xlab(expression(CH[4]~"(µmol"~m^-2~s^-1*")"))+
  scale_fill_manual(values = color.gradient)+
  coord_cartesian(xlim = c(-0.003,0.04))+
  egg::theme_article()+
  theme(legend.position = "none",
        axis.title.y = element_blank())

quants <- part %>%
  filter(!is.na(CH4)) %>%
  mutate(MIU_VALVE = factor(MIU_VALVE, levels = 1:12, 
                            labels = chamber_levels),
         Date = as.Date(DateTime),
         Temp_C = sub("c_[0-9]+_[e|a]", "", MIU_VALVE),
         Temp_C = as.numeric(sub("mb", "0", Temp_C))) %>%
  group_by(Date)  %>%
  filter(length(unique(MIU_VALVE)) == 12) %>%
  group_by(MIU_VALVE, Temp_C) %>%
  summarize(q_50 = quantile(CH4, .50),
            #q_5 = quantile(CH4, .05),
            q_95 = quantile(CH4, .95),
            q_99 = quantile(CH4, .99)) %>%
  pivot_longer(q_50:q_99) %>%
  group_by(name) %>%
  mutate(ref = mean(value[Temp_C == 0]),
         name = as.numeric(sub("q_", "", name)),
         name_txt = paste0(name, "th quantile"),
         name_txt = fct_reorder(name_txt, name)) %>%
  ggplot(aes(x = Temp_C, y = value/ref * 100))+
  geom_hline(yintercept = 100, color = "grey50")+
  geom_smooth(color = "black", fill = "grey70")+
  geom_point(aes(fill = MIU_VALVE), color = "black", 
             shape = 21, size = 2, stroke = 0.5)+
  scale_fill_manual(values = color.gradient, name = "Chamber")+
  ylab(expression(atop(CH[4]~"flux quantile value", "(% of ambient; ppm"~m^-2~s^-1*")")))+
  xlab("Temperature treatment (ºC above ambient)")+
  facet_wrap(~name_txt)+
  egg::theme_article()+
  theme(panel.grid.major = element_line(color = "grey95"))

quants

ggsave("../figures/quantiles.jpg", width = 6, height = 3)
```

Repeating with 2021

```{r}
#fluxes_2021 <- read_csv(here::here("processed_data", "L0_2021_best_fits.csv"))
#fluxes_2025 <- read_csv(here::here("processed_data", "L0_for_dashboard.csv"))

comb <- read_csv(here::here("processed_data", "L0_bestfits_all.csv")) %>%
  mutate(Year = year(TIMESTAMP)) %>%
  filter(CO2_slope_ppm_per_day > 0 |
           (hour(TIMESTAMP) > 6 & hour(TIMESTAMP) < 20)) %>%
  filter(!Year==2021|!MIU_VALVE%in%c(1,8,5),
         !Year==2023|!MIU_VALVE%in%c(10,8,2),
         #Year %in% c(2023, 2021, 2025)#,
         #month(TIMESTAMP) %in% c(6,7)
         )

comb %>%
  mutate(MIU_VALVE = factor(MIU_VALVE, levels = 1:12, 
                            labels = chamber_levels)) %>%
  ggplot(aes(x = CH4_slope_ppm_per_day, y = MIU_VALVE, fill = MIU_VALVE))+
  geom_vline(xintercept = 0, color = "grey50")+
  stat_density_ridges(
    geom = "density_ridges",
    quantiles = 2,
    quantile_lines = TRUE,
    n = 2048,
    rel_min_height = 0.005,
    scale = 0.9
  ) +
  xlab(expression(CH[4]~"(ppm"~m^-2~s^-1*")"))+
  scale_fill_manual(values = color.gradient)+
  coord_cartesian(xlim = c(-2,20))+
  egg::theme_article()+
  facet_wrap(~Year)+
  theme(legend.position = "none",
        axis.title.y = element_blank())

quants <- comb %>%
  filter(!is.na(CH4_slope_ppm_per_day)) %>%
  mutate(MIU_VALVE = factor(MIU_VALVE, levels = 1:12, 
                            labels = chamber_levels),
         Date = as.Date(TIMESTAMP),
         Temp_C = sub("c_[0-9]+_[e|a]", "", MIU_VALVE),
         Temp_C = as.numeric(sub("mb", "0", Temp_C)),
         yday = yday(Date)) %>%
  group_by(yday)  %>%
  filter(length(unique(MIU_VALVE[Year == 2025])) == 12 &
           length(unique(MIU_VALVE[Year == 2021])) == 9&
           length(unique(MIU_VALVE[Year == 2023])) == 9) %>%
  group_by(MIU_VALVE, Temp_C, Year) %>%
  summarize(q_50 = quantile(CH4_slope_ppm_per_day, .50),
            #q_5 = quantile(CH4, .05),
            q_95 = quantile(CH4_slope_ppm_per_day, .95),
            q_99 = quantile(CH4_slope_ppm_per_day, .99),
            n = n(),
            dates = length(unique(Date))) %>%
  pivot_longer(q_50:q_99) %>%
  group_by(name, Year) %>%
  mutate(ref = mean(value[Temp_C == 0]),
         name = as.numeric(sub("q_", "", name)),
         name_txt = paste0(name, "th quantile"),
         name_txt = fct_reorder(name_txt, name)) %>%
  ggplot(aes(x = Temp_C, y = value/ref * 100))+
  geom_hline(yintercept = 100, color = "grey50")+
  geom_smooth(color = "black", fill = "grey70")+
  geom_point(aes(fill = MIU_VALVE), color = "black", 
             shape = 21, size = 2, stroke = 0.5)+
  scale_fill_manual(values = color.gradient, name = "Chamber")+
  ylab(expression(atop(CH[4]~"flux quantile value", "(% of ambient; µmol"~m^-2~s^-1*")")))+
  xlab("Temperature treatment (ºC above ambient)")+
  facet_grid(Year~name_txt)+
  egg::theme_article()+
  theme(panel.grid.major = element_line(color = "grey95"))

quants

ggsave("../figures/quantiles_2021.jpg", width = 6, height = 3)
```

```{r}
chambers <- c(2:4, 6:7,9:12)
quants_rel <- comb %>%
  filter(!is.na(CH4_slope_ppm_per_day),
         MIU_VALVE %in% chambers) %>%
  mutate(MIU_VALVE = factor(MIU_VALVE, levels = chambers, 
                            labels = chamber_levels[chambers]),
         Date = as.Date(TIMESTAMP),
         Temp_C = sub("c_[0-9]+_[e|a]", "", MIU_VALVE),
         Temp_C = as.numeric(sub("mb", "0", Temp_C)),
         yday = yday(Date)) %>%
  group_by(yday)  %>%
  filter(length(unique(MIU_VALVE[Year == 2025])) == 9 &
           length(unique(MIU_VALVE[Year == 2021])) == 9) %>%
  group_by(MIU_VALVE, Temp_C, Year) %>%
  summarize(q_50 = quantile(CH4_slope_ppm_per_day, .50),
            #q_5 = quantile(CH4, .05),
            q_95 = quantile(CH4_slope_ppm_per_day, .95),
            q_99 = quantile(CH4_slope_ppm_per_day, .99),
            n = n(),
            dates = length(unique(Date))) %>%
  pivot_longer(q_50:q_99) %>%
  group_by(name, MIU_VALVE) %>%
  mutate(ref_year = mean(value[Year == 2021]),
         rel_value = value/ref_year) %>%
  filter(Year == 2025) %>%
  group_by(name) %>%
  mutate(ref = mean(rel_value[Temp_C == 0], na.rm = T),
         name = as.numeric(sub("q_", "", name)),
         name_txt = paste0(name, "th quantile"),
         name_txt = fct_reorder(name_txt, name)) %>%
  ggplot(aes(x = Temp_C, y = rel_value/ref * 100))+
  geom_hline(yintercept = 100, color = "grey50")+
  geom_smooth(color = "black", fill = "grey70",
              method = "gam", formula = y ~ s(x, bs = "cs", k = 3))+
  geom_point(aes(fill = MIU_VALVE), color = "black", 
             shape = 21, size = 2, stroke = 0.5)+
  scale_fill_manual(values = color.gradient, name = "Chamber")+
  ylab(expression(atop(CH[4]~"flux quantile value relative to 2021", "(% of ambient; ppm"~m^-2~d^-1*")")))+
  xlab("Temperature treatment (ºC above ambient)")+
  facet_wrap(~name_txt, nrow = 1)+
  egg::theme_article()+
  theme(panel.grid.major = element_line(color = "grey95"))

quants_rel

ggsave("../figures/quantiles_2021_rel.jpg", width = 6, height = 3)
```

```{r}
met <- read_csv(here::here("processed_data","met_all.csv")) 
met %>%
  mutate(yday = yday(TIMESTAMP),
         Year = as.factor(year(TIMESTAMP))) %>%
  filter(Year %in% c(2021,2023, 2025)) %>%
  group_by(yday, Year) %>%
  summarize(AirTC_Avg = mean(AirTC_Avg)) %>%
  ggplot(aes(x = yday, y = AirTC_Avg, color = Year))+
  geom_point(size = 0.5, shape = 21)+
  geom_smooth()
```

```{r}
comb <- read_csv(here::here("processed_data", "L0_bestfits_all.csv")) %>%
  mutate(Year = year(TIMESTAMP)) %>%
  filter(CO2_slope_ppm_per_day > 0 |
           (hour(TIMESTAMP) > 6 & hour(TIMESTAMP) < 20))

comb2 <- comb %>%
  mutate(Year = year(TIMESTAMP)) %>%
  filter(CO2_slope_ppm_per_day > 0 |
           (hour(TIMESTAMP) > 6 & hour(TIMESTAMP) < 20)) #%>%
  #filter(!Year==2021|!MIU_VALVE%in%c(1,8,5))

with_temp <- comb2 %>%
  mutate(time_join = round_date(flux_start, unit = "15 minute")) %>%
  left_join(met %>%
              mutate(time_join = round_date(TIMESTAMP, unit = "15 minute")) %>%
              group_by(time_join) %>%
              summarize(Ta = mean(AirTC_Avg, na.rm = T))) %>%
  filter(!is.na(Ta)) %>%
  mutate(CH4_slope_umol_per_day = CH4_slope_ppm_per_day * #CONVERT TO umolCH4/m2/d
           265.8 / (0.08206*(Ta + 273.15)) / 0.196) %>%
  mutate(Date = as.Date(time_join)) %>%
  rename(CH4_slope_GENX = CH4_slope_umol_per_day) %>%
  select(Date, CH4_slope_GENX, MIU_VALVE) %>%
  na.omit() %>%
  pivot_longer(c(CH4_slope_GENX))

smartx <- read_csv(here::here("Raw_data", "SMARTX CH4 and CO2 fluxes_2016-2025.csv")) %>%
  mutate(Date = as.Date(Date, format = "%m/%d/%Y")) %>%
  rename(CH4_slope_SMARTX = `CH4 flux (umol/m2/d)`) %>%
  select(Date, CH4_slope_SMARTX, Plot) %>%
  pivot_longer(c(CH4_slope_SMARTX))

stats <- with_temp %>%
  bind_rows(smartx) %>%
  group_by(Date) %>%
  filter(!is.na(value),
         sum(grepl("SMARTX", name)) >= 1,
         sum(grepl("GENX", name)) >= 1) %>%
  mutate(veg = ifelse(substr(Plot,1,1) == 4,
                      "C4",
                      "C3")) %>%
  group_by(Date, name) %>%
  summarize(med = median(value),
            q25 = quantile(value, 0.25),
            q75 = quantile(value, 0.75))

stats_veg <- with_temp %>%
  bind_rows(smartx) %>%
  group_by(Date) %>%
  filter(!is.na(value),
         sum(grepl("SMARTX", name)) >= 1,
         sum(grepl("GENX", name)) >= 1) %>%
  mutate(veg = ifelse(substr(Plot,1,1) == 4,
                      "C4",
                      "C3")) %>%
  group_by(Date, name, veg) %>%
  summarize(med = median(value),
            q25 = quantile(value, 0.25),
            q75 = quantile(value, 0.75)) 

stats_filled <- stats_veg %>%
  filter(is.na(veg)) %>%
  mutate(veg = "C3") %>%
  bind_rows(stats_veg %>%
              mutate(veg = ifelse(is.na(veg),"C4", veg))) %>%
  pivot_wider(names_from = name, values_from = c(med, q25, q75)) %>%
  mutate(Year = as.factor(year(Date)))

stats %>%
  pivot_wider(names_from = name, values_from = c(med, q25, q75)) %>%
  mutate(Year = as.factor(year(Date))) %>%
  ggplot(aes(x = med_CH4_slope_GENX, y = med_CH4_slope_SMARTX,
             color = Year))+
  geom_errorbar(aes(xmin = q25_CH4_slope_GENX,
                    xmax = q75_CH4_slope_GENX))+
  geom_errorbar(aes(ymin = q25_CH4_slope_SMARTX,
                    ymax = q75_CH4_slope_SMARTX))+
  geom_point(shape = 21, color = "black", aes(fill = Year))+
  geom_abline()

stats_filled %>%
  ggplot(aes(y = med_CH4_slope_GENX, x = med_CH4_slope_SMARTX,
             color = Year))+
  geom_errorbar(aes(ymin = q25_CH4_slope_GENX,
                    ymax = q75_CH4_slope_GENX))+
  geom_errorbar(aes(xmin = q25_CH4_slope_SMARTX,
                    xmax = q75_CH4_slope_SMARTX))+
  geom_point(shape = 21, color = "black", aes(fill = Year))+
  geom_smooth(method = "lm", se = F)+
  geom_abline()+
  facet_wrap(~veg)
```

```{r}
wl <- read_csv(here::here("processed_data", "water_level.csv"))

wl %>%
  filter(year(TIMESTAMP) == 2023,
         as.Date(TIMESTAMP) < as.Date("2023-07-01"),
         as.Date(TIMESTAMP) > as.Date("2023-06-28"),) %>%
  ggplot(aes(x = TIMESTAMP, y = Depth_cm))+
  geom_line()
```

```{r}
wl <- read_csv(here::here("processed_data", "water_level.csv"))

wl %>%
  mutate(yday = yday(TIMESTAMP),
         year = year(TIMESTAMP)) %>%
  filter(yday < yday(as.Date("2021-07-31")),
         yday > yday(as.Date("2021-07-01"))) %>%
  ggplot(aes(x = TIMESTAMP, y = Depth_cm))+
  geom_line()+
  facet_wrap(~year, scales = "free_x")

wl %>%
  mutate(yday = yday(TIMESTAMP),
         year = year(TIMESTAMP)) %>%
  filter(yday < yday(as.Date("2021-07-31")),
         yday > yday(as.Date("2021-05-01"))) %>%
  ggplot(aes(x = TIMESTAMP, y = Salinity_PSU))+
  geom_line()+
  facet_wrap(~year, scales = "free_x")
```